[build]
  publish = "dist"                  # Tells Netlify where your static site is (React build output)
  functions = "netlify/functions"  # Location of Netlify Functions

[dev]
  functions = "netlify/functions"
  port = 8888
  command = "vite"
